<?php
/* $Id$ */

/**
 * @file
 * Module that plugs in Campaign Monitor functionality to your Drupal web site.
 * For Campaign Monitor information see: http://www.campaignmonitor.com/
 *
 * This module uses the CampaignMonitor PHP API. For all credit and information
 * about this PHP API see By ssherriff: http://code.google.com/p/campaignmonitor-php/
 */
 
define('CM_SUBSCRIPTION_SUCCESS',   t('Thank you, you have been successfully subscribed.'));
define('CM_SUBSCRIPTION_FAILURE',   t('We were unable to subscribe you at this time. Please try again later.'));
define('CM_UNSUBSCRIPTION_SUCCESS', t('Thank you, you have been successfully unsubscribed.'));
define('CM_UNSUBSCRIPTION_FAILURE', t('We were unable to unsubscribe you at this time. Please try again later.'));
 
 @require_once(drupal_get_path('module', 'campaignmonitor') .'/lib/CMBase.php');

/* DRUPAL HOOKS */
/* hook_help */
function campaignmonitor_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/campaignmonitor':
      return '<p>'. t('Use your API key and other keys to have users register for a mailing list setup through Campaign Monitor.') . '</p>';
  }
}


/* hook_perm */
function campaignmonitor_perm() {
  return array('administer campaignmonitor', 'access archive', 'join newsletter');
}

/* hook_menu */
function campaignmonitor_menu() {
  $items = array();
  $items['admin/settings/campaignmonitor'] = array(
    'title' => t('Campaign Monitor'),
    'description' => t('Setup Campaign Monitor values.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('campaignmonitor_admin'),
    'access arguments' => array('administer campaignmonitor'),
    'type' => MENU_NORMAL_ITEM);
  $items['newsletter_archive'] = array(
    'title' => t('Newsletter Archive'),
    'page callback' => 'campaignmonitor_newsletter_archive',
    'access arguments' => array('access archive'),
    'type' => MENU_SUGGESTED_ITEM);
  $items['user/%user/newsletters'] = array(
    'title' => t('My Newsletters'),
    'page callback' => 'campaignmonitor_user_page',
		'access arguments' => array('join newsletter'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );
  
  $items['campaignmonitor/js'] = array(
		'title' => 'Javascript Lists',
		'page callback' => 'campaignmonitor_lists_js',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/* hook_form_alter */
function campaignmonitor_form_alter(&$form, $form_state, $form_id) {
  $display_on = variable_get('campaignmonitor_display_on', array());
  if (('contact_mail_page' == $form_id && $display_on['contact'] != '0') || ('user_register' == $form_id && $display_on['registration'] != '0') && user_access('join newsletter')) {
    $api_key = variable_get('campaignmonitor_api_key', '');
  	$client_id = variable_get('campaignmonitor_client_id', '');
		$list_ids = campaignmonitor_get_available_lists();
  	$lists = _campaignmonitor_get_lists($api_key, $client_id); 
		
		$options = array();
		//$default_values = array();
		foreach ($list_ids as $list_id => $list) {
			if($list != '0') {
				//$default_values[] = $list_id;
				$options[$list_id] = $lists[$list_id];
			}
		}
		
		$form['subscribe_newsletter'] = array(
		    '#type'          => 'checkboxes',
				'#title'         => t(variable_get('campaignmonitor_checkboxdisplaytext', 'Available Newsletters')),
				'#options'       => $options,
		    //'#default_value' => $default_values,
				'#weight'        => 99,
		);
  
    $form['submit']['#weight'] = 100;
		
		$form['#submit'][] = '_campaignmonitor_altered_form_submit';
  }
}

function _campaignmonitor_altered_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
	$listids = $form_values['subscribe_newsletter'];

  if (count($listids) > 0) {
    if ('contact_mail_page' == $form_id) {
      $form_values['message'] .= "\n\n" . t('Subscribed to newsletter(s).');
    }

    // Replace api_key and list_id with your own details
    $api_key = variable_get('campaignmonitor_api_key', '');
		
    $email = $form_values['mail'];
    $name = $form_values['name'];
		
		foreach($listids as $list_id) {
 			_campaignmonitor_add_subscriber($api_key, $list_id, $name, $email);
		}
  }
}

/**
 * Implementation of hook_block()
 */
function campaignmonitor_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
	  return campaignmonitor_block_list();
    
    case 'configure':
    case 'save':
      // no additional configuration options
      break;
    
    case 'view':
    default:
	  	$lists = _campaignmonitor_get_lists(variable_get('campaignmonitor_api_key',''), variable_get('campaignmonitor_client_id',''));
	  	$block['subject'] = $lists[$delta];
      $block['content'] = theme('campaignmonitor_block_content', $delta);
      return $block;
  }
}

/**
 * Implementation of hook_theme()
 */
function campaignmonitor_theme() {
  return array(
    'campaignmonitor_block_content' => array(
    	'template' => 'campaignmonitor-block-content',
	  	'arguments' => array('list_id' => NULL),
    ),
  );
}

/* END DRUPAL HOOKS */

/* MODULE FUNCTIONS */

/**
 * Returns a list of blocks in a form suitable for hook_block() when $op == list:
 * A block is returned for each CampaignMonitor list chosen in admin settings
 */
function campaignmonitor_block_list() {
  $api_key = variable_get('campaignmonitor_api_key', '');
  $client_id = variable_get('campaignmonitor_client_id', '');
  $list_ids = campaignmonitor_get_available_lists();
	//watchdog('campaign monitor','lists: %lists',array('%lists' => print_r($list_ids,true)));
  $lists = _campaignmonitor_get_lists($api_key, $client_id); 
  foreach ($list_ids as $list_id => $list) {
  	// If list==0 that means that list is not chosen, don't create a block
  	if($list != '0') {
      $blocks[$list_id]['info'] = t('Subscribe to @list_name', array('@list_name' => $lists[$list_id]));
		}
  }
  return $blocks;
}

function campaignmonitor_admin() {

  $form['campaignmonitor_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#default_value' => variable_get('campaignmonitor_api_key', ''),
    '#required' => TRUE,
    '#size' => 50,
    '#maxlength' => 200,
    '#description' => t('Your Campaign Monitor API Key. See <a href="http://www.campaignmonitor.com/api/required/">documentation</a>.')
  );
  
  $form['campaignmonitor_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Client ID'),
    '#default_value' => variable_get('campaignmonitor_client_id', ''),
    '#required' => TRUE,
    '#size' => 50,
    '#maxlength' => 200,
    '#description' => t('Your Campaign Monitor Client ID. See <a href="http://www.campaignmonitor.com/api/required/">documentation</a>.')
  );
  
  // Add a wrapper for the lists and selection radio buttons.
  $form['campaignmonitor_lists_wrapper'] = array(
  	'#tree' => FALSE,
		'#prefix' => '<div class="clear-block" id="campaignmonitor-lists-wrapper">',
		'#suffix' => '</div>',
  );

  $form['campaignmonitor_lists_wrapper']['campaignmonitor_available_lists'] = array(
		'#title' => t('Choose which lists you wish to make available'),
		'#type' => 'radios',
		'#options' => array(
		  'all' => 'All lists for this client',
		  'some' => 'I want to select specific lists for this client',
	  	),
		'#default_value' => variable_get('campaignmonitor_available_lists', 'all'),
		'#description' => t('Please enter Client ID and select which lists you wish to make available.'),
		'#submit' => array('_campaignmonitor_fetch_lists_submit'), // if no JS
		'#ahah' => array(
		  'path' => 'campaignmonitor/js',
		  'wrapper' => 'campaignmonitor-lists',
		  'method' => 'replace',
		  'effect' => 'fade',
		),
  );

  // Container for the list of lists
  if(variable_get('campaignmonitor_available_lists', 'all') == 'some') {
		$form['campaignmonitor_lists_wrapper']['campaignmonitor_list_ids'] = array(
			'#type' => 'checkboxes',
			'#prefix' => '<div id="campaignmonitor-lists">',
			'#options' => _campaignmonitor_get_lists(variable_get('campaignmonitor_api_key',''), variable_get('campaignmonitor_client_id','')),
			'#default_value' => variable_get('campaignmonitor_list_ids', array()),
			'#suffix' => '</div>',
		);
  } 
  else {
	  $form['campaignmonitor_lists_wrapper']['campaignmonitor_list_ids'] = array(
			'#type' => 'checkboxes',
			'#prefix' => '<div id="campaignmonitor-lists">',
			'#options' => array(),
			'#suffix' => '</div>',
	  );
  }
  
  $form['campaignmonitor_display_on'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Display on Options'),
    '#default_value' => variable_get('campaignmonitor_display_on', array()),
    '#options' => array(
      'contact' => t('Contact Page'),
      'registration' => t('Registration Page')
    ),
    '#description' => t('Choose which forms you want to display the Join Newsletter checkbox.')
  );
  
  $form['campaignmonitor_checkboxdisplaytext'] = array(
    '#type' => 'textfield',
    '#title' => t('Display Text for Checkbox'),
    '#default_value' => variable_get('campaignmonitor_checkboxdisplaytext', 'Join our Newsletter?'),
    '#size' => 50,
    '#maxlength' => 50,
    '#description' => t("This text will display next to the checkbox on the selected forms.")
  );
  
  $form['campaignmonitor_userpagedisplaytext'] = array(
    '#type' => 'textfield',
    '#title' => t('Display Text for User Page'),
    '#default_value' => variable_get('campaignmonitor_userpagedisplaytext', 'Available Newsletters'),
    '#size' => 50,
    '#maxlength' => 50,
    '#description' => t("This text will display next to the checkbox on the user profile page.")
  );
  
  $form['campaignmonitor_pastcampaignurl'] = array(
    '#type' => 'textfield',
    '#title' => t('Past Campaign URL'),
    '#default_value' => variable_get('campaignmonitor_pastcampaignurl', ''),
    '#size' => 100,
    '#maxlength' => 100,
    '#description' => t("This is required if you want to use the page that displays past campaigns. You can find this value if you go to Manage Clients, click on the client, go to the link that tells you how to display past campaigns, then copy the URL ONLY from the html given. The URL is in between the src=\"\" value.")
  );
  
  $form['campaignmonitor_connection_timeout'] = array(
    '#type' => 'textfield',
    '#title' => t('Connection timeout'),
    '#default_value' => variable_get('campaignmonitor_connection_timeout', 15),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t("If your server can't get through to the API, or the API server is down, this is the amount of time until the connection times out in seconds. Default is 15 seconds.")
  );
  
  $form['#submit'][] = 'campaignmonitor_admin_submit';
  
  return system_settings_form($form);
}

function campaignmonitor_admin_submit($form, &$form_state) {
  // rebuild the block db table as we've possibly changed the blocks
  _block_rehash();
}

function campaignmonitor_subscribe_form(&$form_state, $list_id) {
  global $user;
	$name = '';
	$email = '';
	$subscriber_custom_fields = array();
	$default = false;
	
	// Check if the profile module is installed. If it is, use the name element of the profile
	if (module_exists("profile")) {
  	profile_load_profile($user->uid);
		$name = $user->profile_name;
	}
  if ($user->uid != 0) {
    $email = $user->mail;
    if (_campaignmonitor_is_subscribed(variable_get('campaignmonitor_api_key', ''), 
			$list_id, $email)) {
      $default = true;
			// Also if subscribed get name
			$subscriber = _campaignmonitor_get_subscriber(variable_get('campaignmonitor_api_key', ''),
			  $list_id, $email);
				//watchdog('campaignmonitor', 'subscriber: %subscriber', array('%subscriber' => print_r($subscriber, true)), WATCHDOG_DEBUG);
			$name = $subscriber['name'];
    }
    else {
      $default = false;
    }
  
  }
	
  $form['name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Name'),
    '#size'          => 20,
    '#maxlength'     => 50,
    '#required'      => TRUE,
		'#default_value' => $name,
  );
  $form['email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Email'),
    '#size'          => 20,
    '#maxlength'     => 100,
    '#required'      => TRUE,
		'#default_value' => $email,
  );
	
	$custom_fields = _campaignmonitor_get_custom_fields(variable_get('campaignmonitor_api_key', ''), $list_id);
	//watchdog('campaignmonitor', 'custom fields: %retval', array('%retval' => print_r($custom_fields, true)), WATCHDOG_INFO);
	foreach($custom_fields as $field) {
		$key = str_replace('[','',$field['Key']);
		$key = str_replace(']','',$key);
	  if($field['FieldName'] == 'Text') {
	    $form[$key] = array(
        '#type'          => 'textfield',
        '#title'         => $field['FieldName'],
        '#size'          => 20,
        '#maxlength'     => 100,
		    '#default_value' => $subscriber['CustomFields'][$field['FieldName']],
      );
		} else if($field['DataType'] == 'MultiSelectOne') {
		  $options = array();
		  foreach($field['FieldOptions']['string'] as $option) {
				$options[$option] = $option;
			}
			$_defaultvalue = $subscriber['CustomFields'][$field['FieldName']];
			if(empty($_defaultvalue)) {
				$defaultvalue = '';
			} else {
				$defaultvalue = $_defaultvalue;
			}
	    $form[$key] = array(
        '#type'          => 'select',
        '#title'         => $field['FieldName'],
				'#options'       => $options,
		    '#default_value' => $defaultvalue,
      );
		} else if($field['DataType'] == 'MultiSelectMany') {
		  $options = array();
		  foreach($field['FieldOptions']['string'] as $option) {
				$options[$option] = $option;
			}
			watchdog('campaignmonitor', 'options: %retval', array('%retval' => print_r($options, true)), WATCHDOG_INFO);
			$_defaultvalues = $subscriber['CustomFields'][$field['FieldName']];
			if(empty($_defaultvalues)) {
			  $defaultvalues = array();
			} else if (!is_array($_defaultvalues)) {
				$defaultvalues = array();
				$defaultvalues[] = $_defaultvalues;
			} else  {
				//watchdog('campaignmonitor', 'default value: %retval', array('%retval' => print_r($_defaultvalues, true)), WATCHDOG_DEBUG);
				$defaultvalues = array();
				foreach($_defaultvalues as $dv) {
					$defaultvalues[] = $dv;
				}
			}
	    $form[$key] = array(
        '#type'          => 'checkboxes',
        '#title'         => $field['FieldName'],
				'#options'       => $options,
		    '#default_value' => $defaultvalues,
      );
		}
	}
  
  /*$form['unsubscribe_newsletter'] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Unsubscribe'),
    '#default_value' => $default,
  );*/
  
  $form['list_id'] = array(
    '#type' => 'hidden',
    '#value' => $list_id,
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  return $form;
}

function campaignmonitor_subscribe_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  
  // Replace api_key with your own details
  $api_key = variable_get('campaignmonitor_api_key', '');
  
  $list_id = $form_values['list_id'];
  $name = $form_values['name'];
  $email = $form_values['email'];
	$custom_field_array = array();
	
	watchdog('campaignmonitor', 'form_values: %retval', array('%retval' => print_r($form_values, true)), WATCHDOG_INFO);

  // any cases other then these are when things are unchanged
  if (!$form_values['unsubscribe_newsletter']) {
    // this is the case where they now want to be subscribed, and weren't before
		$custom_fields = _campaignmonitor_get_custom_fields($api_key, $list_id);
		foreach($custom_fields as $field) {
			$key = str_replace('[','',$field['Key']);
			$key = str_replace(']','',$key);
		  $custom_field_array[$field['FieldName']] = $form_values[$key]; 
		}
		
    _campaignmonitor_add_subscriber($api_key, $list_id, $name, $email, $custom_field_array);
  }
  else if ($form_values['unsubscribe_newsletter']) {
    // this is the case where they don't want to be subscribed, and were before
    _campaignmonitor_remove_subscriber($api_key, $list_id, $email);
  }
}

function campaignmonitor_newsletter_archive() {
  $url = variable_get('campaignmonitor_pastcampaignurl', '');
  if ($url == '') {
    $content = '<p>The past campaign URL has not been set. Please set this in the administration pages.</p>';
  }
  else{
    $content = '<script type="text/javascript" src="'. variable_get('campaignmonitor_pastcampaignurl', '') .'"></script>';
  }
  return $content;
}

function campaignmonitor_user_page() {
  return drupal_get_form('campaignmonitor_user_form');
}

function campaignmonitor_user_form() {
  global $user;
  // Replace api_key and list_id with your own details
  $api_key = variable_get('campaignmonitor_api_key', '');
  $client_id = variable_get('campaignmonitor_client_id', '');
	$list_ids = campaignmonitor_get_available_lists();
  $lists = _campaignmonitor_get_lists($api_key, $client_id); 
  
  $email = $user->mail;
	
	$options = array();
	$default_values = array();

	foreach ($list_ids as $list_id => $list) {
		if($list != '0') {
			if (_campaignmonitor_is_subscribed($api_key, $list_id, $email, true)) {
		    $default = true;
				$default_values[] = $list_id;
		  }
		  else {
		    $default = false;
		  }
			$options[$list_id] = $lists[$list_id];
		  
		  $form['is_subscribed_'.$list_id] = array(
		    '#type'          => 'hidden',
		    '#default_value' => $default,
		  );
		}
	}
	$form['subscribe_newsletter'] = array(
		    '#type'          => 'checkboxes',
				'#title'         => variable_get('campaignmonitor_userpagedisplaytext', 'Available Newsletters'),
				'#options'       => $options,
		    '#default_value' => $default_values,
		  );
	
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

function campaignmonitor_user_form_submit($form, &$form_state)  {
  $form_values = $form_state['values'];
  global $user;
  // Check if the profile module is installed. If it is, use the name element of the profile
	if (module_exists("profile")) {
  	profile_load_profile($user->uid);
		$profile_name = $user->profile_name;
	}
	
  $api_key = variable_get('campaignmonitor_api_key', '');
  $client_id = variable_get('campaignmonitor_client_id', '');
	$lists = _campaignmonitor_get_lists($api_key, $client_id);
	$chosen_lists = campaignmonitor_get_available_lists();
	$subscribe = $form_values['subscribe_newsletter'];
  
  $name = $profile_name;
  $email = $user->mail;

	foreach($chosen_lists as $list_id => $listvalue) {
		if($listvalue != '0') {
			// if subscribed, add if not already subscribed
		  if ($subscribe[$list_id] != null && !$form_values['is_subscribed_'.$list_id]) {
		  	//watchdog('campaignmonitor','being subscribed');
		    _campaignmonitor_add_subscriber($api_key, $list_id, $name, $email);
		  }
			// if not subscribed, and was subscribed before
		  else if ($subscribe[$list_id] == null && $form_values['is_subscribed_'.$list_id]) {
		  	//watchdog('campaignmonitor','being unsubscribed');
		    _campaignmonitor_remove_subscriber($api_key, $list_id, $email);
		  }
		}
	}
}

function campaignmonitor_get_available_lists() {
	$list_ids = variable_get('campaignmonitor_list_ids', array());
	$toggle = variable_get('campaignmonitor_available_lists', 'all');
	if($toggle == 'some') {
		return $list_ids;
	}
	else {
		$api_key = variable_get('campaignmonitor_api_key', '');
  	$client_id = variable_get('campaignmonitor_client_id', '');
		$ret = array();
		$lists = _campaignmonitor_get_lists($api_key, $client_id);
		foreach($lists as $list_id => $list_name) {
			$ret[$list_id] = $list_id;
		}
		return $ret;
	}
}

/* END MODULE FUNCTIONS */

/* TEMPLATE FUNCTIONS */

/**
 * Block template preprocessor
 */
function template_preprocess_campaignmonitor_block_content(&$variables) {
  $variables['form'] = drupal_get_form('campaignmonitor_subscribe_form', $variables['list_id']);
  
  if (user_access('access archive')) {
    $variables['archive_link'] =  l('Newsletter Archive', 'newsletter_archive');
  }
  else {
    $variables['archive_link'] = '';
  }
}

/* END TEMPLATE FUNCTIONS */

/* SOAP CALLS AND HELPERS */

function _campaignmonitor_is_subscribed($api_key, $list_id, $email, $show_errors = FALSE) {
  $retval = FALSE;
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );
  
  $result = $cm->subscribersGetIsSubscribed($email, $list_id);

  if ($result['anyType']['Code'] != 0) {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    $retval = FALSE;
    if ($show_errors) {
      drupal_set_message(t("There is an error with the newsletter server. Please try again later."), 'error');
    }
  } 
  else if ($result['anyType'] == 'False') {
    $retval = FALSE;
  }
  else if ($result['anyType'] == 'True') {
    $retval = TRUE;
  }
  return $retval;
}

function _campaignmonitor_add_subscriber($api_key, $list_id, $name, $email, $custom_fields = array(), $show_errors = FALSE) {
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );
	
	if(count($custom_fields) > 0) {
	  $result = $cm->subscriberAddAndResubscribeWithCustomFields($email, $name, $custom_fields);
	} else {
    $result = $cm->subscriberAddAndResubscribe($email, $name);
	}
  if ($result['anyType']['Code'] != 0) {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    drupal_set_message(t("There was an error joining to newsletter."), 'error');
  }
  else {
    drupal_set_message(t("You have successfully been added."), 'status');
  }
}

function _campaignmonitor_remove_subscriber($api_key, $list_id, $email, $show_errors = FALSE) {
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );

  $result = $cm->subscriberUnsubscribe($email);
  if ($result['Result']['Code'] == 0) {
    drupal_set_message(t("You have successfully been unsubscribed."), 'status');
  }
  else {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    drupal_set_message(t("There was an error unsubscribing from newsletter."), 'error');
  }
}

function _campaignmonitor_get_subscriber($api_key, $list_id, $email, $show_errors = FALSE) {
  $retval = array("name" => '', "email" => $email);
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );
	
	$result = $cm->subscriberGetSingleSubscriber($list_id, $email);

  /*$result = $cm->makeCall( 'Subscribers.GetSingleSubscriber', array(
                 'params' => array(
                 'ListID' => $list_id,
                 'EmailAddress' => $email)
                  )
                );*/

  if ($result['anyType']['Code'] != 0) {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    if ($show_errors) {
      drupal_set_message(t("There is an error with the newsletter server. Please try again later."), 'error');
    }
  }
  else {
	  watchdog('campaignmonitor', 'retval: %retval', array('%retval' => print_r($result, true)), WATCHDOG_INFO);
    $retval['name'] = $result['anyType']['Name'];
		$custom_fields = array();
		$c = $result['anyType']['CustomFields']['SubscriberCustomField'];
		//watchdog('campaignmonitor', 'customfields: %retval', array('%retval' => print_r($c, true)), WATCHDOG_INFO);
		if (!empty($c['Key'])) {
		  $custom_fields = array();
			$custom_fields[$c['Key']] = $c['Value'];
		} 
		else {
			if(!empty($c)) {
		  foreach($c as $field) {
			  if(!empty($custom_fields[$field['Key']])) {
				  //watchdog('campaignmonitor', 'not empty');
				  if(is_array($custom_fields[$field['Key']])) {
					//watchdog('campaignmonitor', 'is array');
					  $values = $custom_fields[$field['Key']];
					}
					else {
					//watchdog('campaignmonitor', 'not array');
					  $values = array();
						//$values[$field['Key']] = $custom_fields[$field['Key']];
						$values[] = $custom_fields[$field['Key']];
					}
					$values[] = $field['Value'];
				  $custom_fields[$field['Key']] = $values;
				}
				else {
			    $custom_fields[$field['Key']] = $field['Value'];
			  }
		  } }
		}
		$retval['CustomFields'] = $custom_fields;
  }
  return $retval;
}

function _campaignmonitor_get_lists($api_key, $client_id) {
	$retval = array();
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );

  $result = $cm->clientGetLists();

  if ($result['anyType']['Code'] != 0) {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    if ($show_errors) {
      drupal_set_message(t("There is an error with the newsletter server. Please try again later."), 'error');
    }
  }
  else {
		 //watchdog('campaignmonitor', 'retval: %retval', array('%retval' => print_r($result, true)), WATCHDOG_INFO);
    if (!empty($result['anyType']['List'])) {
				$lists = $result['anyType']['List'];
				// if there is only one list
				if (!empty($lists['ListID'])) {
					$retval[$lists['ListID']] = $lists['Name'];
				}
				else {
					foreach($lists as $list) {
						$retval[$list['ListID']] = $list['Name'];
				  }
			  }
		}
  }
  return $retval;
}

function _campaignmonitor_get_custom_fields($api_key, $list_id) {
	$retval = array();
  $cm = new CampaignMonitor($api_key, $client_id, $campaign_id, $list_id );

  $result = $cm->listGetCustomFields( $list_id );

  if ($result['anyType']['Code'] != 0) {
	  watchdog('campaignmonitor', 'Code - %code, Message - %message', 
		  			array('%code' => $result['anyType']['Code'], '%message' => $result['anyType']['Message']));
    if ($show_errors) {
      drupal_set_message(t("There is an error with the newsletter server. Please try again later."), 'error');
    }
  }
  else {
		watchdog('campaignmonitor', 'retval: %retval', array('%retval' => print_r($result, true)), WATCHDOG_INFO);
    if (!empty($result['anyType']['ListCustomField'])) {
				
				// if there is only one list
				if (!empty($result['anyType']['ListCustomField']['FieldName'])) {
					$retval = array();
					$retval[] = $result['anyType']['ListCustomField'];
				}
				else {
					$retval = $result['anyType']['ListCustomField'];
					//foreach($lists as $list) {
					//	$retval[$list['ListID']] = $list['Name'];
				  //}
			  }
		}
  }
  return $retval;
}

function _campaignmonitor_fetch_lists_submit($form, &$form_state) {
  // @todo:
}
/* END SOAP CALLS AND HELPERS */

/* JAVASCRIPT FUNCTIONS */
function campaignmonitor_lists_js() {
  $form_state = array(
	'storage' => NULL,
	'submitted' => FALSE,
  );
  $form_build_id = $_POST['form_build_id'];

  // Get the form from the cache.
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);

  // We will run some of the submit handlers so we need to disable redirecting.
  $form['#redirect'] = FALSE;

  // We need to process the form, prepare for that by setting a few internal variables.
  $form['#post'] = $_POST;
  $form['#programmed'] = FALSE;
  $form_state['post'] = $_POST;

  // Build, validate and if possible, submit the form.
  drupal_process_form($form_id, $form, $form_state);

  // This call recreates the form relying solely on the form_state that the
  // drupal_process_form set up.
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);

  // Render the new output.
  $lists_form = $form['campaignmonitor_lists_wrapper']['campaignmonitor_list_ids'];
  unset($choice_form['#prefix'], $choice_form['#suffix']); // Prevent duplicate wrappers.

  $lists_type = $form_state['post']['campaignmonitor_available_lists'];
  switch ($lists_type) {
	case 'all':
	  $output = theme('status_messages') . t('All the lists from this client will be available to the users.');
	  break;

	case 'some':
	  // Make sure the API key and Client ID are filled in.
	  if (empty($form_state['post']['campaignmonitor_client_id']) || empty($form_state['post']['campaignmonitor_api_key'])) {
			form_set_error('fetch_lists', t('Please enter the API key and client ID first.'));
			$output = theme('status_messages');
	  }
	  else {
			$lists = _campaignmonitor_get_lists($form_state['post']['campaignmonitor_api_key'], $form_state['post']['campaignmonitor_client_id']);
			$output = theme('status_messages') . '<div class="form-checkboxes">';
			$i = 0;
			foreach ($lists as $key => $value) {
			  $output .= '<div id="edit-lists-' . $key . '-wrapper" class="form-item">'
				. '<label class="option"><input type="checkbox" name="campaignmonitor_list_ids[' . $key . ']" value="'.$key.'" /></label> ' . $value
				. '</div>';
			  $i++;
			}
			$output .= '</div>';
	  }
	  break;
	}

	drupal_json(array('status' => TRUE, 'data' => $output));
  }

/* END JAVASCRIPT FUNCTIONS */