<?php

/*
 * @file
 * Enable users to select which newsletter lists they want to subscribe on the
 * registration page.
 */

/**
 * Implements hook_perm().
 */
function campaignmonitor_registration_permission() {
  return array(
    'access campaign monitor registration' => array(
      'title' => t('Access Campaign Monitor on registration page'),
      'description' => t('Allow user to subscribe to lists on the registration page.'),
    ),
  );
}

/**
 * Hooks into the registration form and adds the option to select on of the
 * lists avaliable from campaign monitor on registration.
 */
function campaignmonitor_registration_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  // Get connected to the API and get lists.
  $cm = CampaignMonitor::getConnector();
  $lists = $cm->getLists();

  // Build options for the form selector.
  $options = array();
  foreach ($lists as $key => $list) {
    $options[$key] = $list['name'];
  }

  if (!empty($options)) {
    $form['campaignmonitor'] = array(
      '#type' => 'fieldset',
      '#title' => t('News lists'),
    );

    $form['campaignmonitor']['campaignmonitor_lists'] = array(
      '#type' => 'checkboxes',
      '#description' => t('Select the news lists, that you want to subscribe to from campaign monitor.'),
      '#options' => $options,
    );

    $form['#validate'][] = 'campaignmonitor_registration_form_user_register_submit';
  }
}

/**
 * Validation form, where information about the selected list is submitted to
 * campaign monitor. It's done in a validation form to eable better user
 * feedback in the case of failure to communicate with the servers.
 */
function campaignmonitor_registration_form_user_register_submit($form, &$form_state) {
  if (isset($form_state['values']['campaignmonitor_lists'])) {
    // Get connected to the API and get lists.
    $cm = CampaignMonitor::getConnector();
    $lists_info = $cm->getLists();

    // Find the selected lists, if any.
    foreach ($form_state['values']['campaignmonitor_lists'] as $list_id => $selected) {
      if ($selected) {
        // Try to subscribe to the list.
        if (!$cm->subscribe($list_id, $form_state['values']['mail'], $form_state['values']['name'])) {
          form_set_error('', t('You where not subscribed to the list, please try again later.'));
          return FALSE;
        }
        drupal_set_message(t('You are now subscribed to the "@list" list.', array('@list' => $lists_info[$list_id]['name'])), 'status');
      }
    }

    // Remove it from the form before the submit functions takes over (might not be needed).
    unset($form_state['values']['campaignmonitor_lists']);
  }
}