<?php

/*
 * @file
 * Enable users to select which newsletter lists they want to subscribe to in a
 * tab on their profile page.
 */

/**
 * Implements hook_perm().
 */
function campaignmonitor_user_permission() {
  return array(
    'access campaign monitor user' => array(
      'title' => t('Access Campaign Monitor on user page'),
      'description' => t('Allow user to subscribe to lists on the user page.'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function campaignmonitor_user_menu() {
  $items = array();

  $items['user/%user/newsletters'] = array(
    'title' => 'My Newsletters',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('campaignmonitor_user_form'),
    'access callback' => 'campaignmonitor_user_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );

  return $items;
}

/**
 * Access callback for the user newsletters page.
 */
function campaignmonitor_user_access($account) {
  global $user;
  if ($user->uid && $user->uid == $account->uid && user_access('access campaign monitor user')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Builds the selection list for the user profile page.
 *
 * @return array $form
 */
function campaignmonitor_user_form() {
  global $user;
  $form = array();

  // Get connected to the API and get lists.
  $account = variable_get('campaignmonitor_account', FALSE);
  $cm = CampaignMonitor::getConnector($account['api_key'], $account['client_id']);
  $lists = $cm->getLists();

  // Build options for the form selector.
  $options = array();
  $default = array();
  foreach ($lists as $key => $list) {
    $options[$key] = $list['name'];

    // Check if the user is subscribed to the current list.
    $default[$key] = 0;
    if ($cm->isSubscribed($key, $user->mail)) {
      $default[$key] = $key;
    }
  }

  $form['lists'] = array(
    '#type' => 'checkboxes',
    '#title' => t('News lists'),
    '#description' => t('Select the news lists, that you want to subscribe to from campaign monitor.'),
    '#options' => $options,
    '#default_value' => $default,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update subscriptions'),
  );

  $form['#submit'] = array('campaignmonitor_user_form_submit');
  $form['#validate'] = array('campaignmonitor_user_form_validate');

  return $form;
}

function campaignmonitor_user_form_validate($form, &$form_state) {
  global $user;

  // Get connected to the API and get lists.
  $account = variable_get('campaignmonitor_account', FALSE);
  $cm = CampaignMonitor::getConnector($account['api_key'], $account['client_id']);
  $lists_info = $cm->getLists();

  // Loop through the lists
  foreach ($form_state['values']['lists'] as $list_id => $selected) {
    if ($selected) {
      // If not subscribed, subscribe else do nothing. The subscribe state is
      // already in the cache, so it cheaper to check then re-subscribe.
      if (!$cm->isSubscribed($list_id, $user->mail)) {
        if (!$cm->subscribe($list_id, $user->mail, $user->name)) {
          form_set_error('', t('You where not subscribed to the list, please try again later.'));
          return FALSE;
        }
        drupal_set_message(t('You are now subscribed to the "@list" list.', array('@list' => $lists_info[$list_id]['name'])), 'status');
      }
    }
    else {
      // Maybe this is an unsubscribe.
      if ($cm->isSubscribed($list_id, $user->mail)) {
        if (!$cm->unsubscribe($list_id, $user->mail)) {
          form_set_error('', t('You where not unsubscribed to the list(s), please try again later.'));
          return FALSE;
        }
        drupal_set_message(t('You are now removed from the "@list" list.', array('@list' => $lists_info[$list_id]['name'])), 'status');
      }
    }
  }
}